image: "harbor.shopeemobile.com/shopee/lls-ci-base:1.13"

stages:
  - lint

lint:
  stage: lint
  script:
    - /usr/bin/golangci-lint/golangci-lint run -v --timeout=5m --skip-files "_test\.go" ./...
