run:
  skip-dirs:
    - docs

linters-settings:
  maligned:
    suggest-new: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch

linters:
  disable:
    - godox
    - wrapcheck
    - gochecknoglobals
    - funlen
  enable-all: true