run:
  skip-dirs:
    - docs

linters-settings:
  maligned:
    suggest-new: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch

linters:
  disable:
    - gosec
    - wrapcheck
    - gochecknoglobals
    - funlen
    - exhaustivestruct
  enable-all: true